"""The companion's LLM client must be attributable and provenance-aware.

Same two gateway facts as the main app, seen from the async side: the gateway
files telemetry by ``X-Service-Name``, and it may serve a different model than
the one requested. A plan that was generated by a substituted model must not
look like it came from the operator's configured one.
"""

from __future__ import annotations

import sys
import unittest
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[2]))

import httpx  # noqa: E402

from hive_companion.llm import ChatClient, LLMError  # noqa: E402


def _transport(handler) -> httpx.AsyncClient:
    return httpx.AsyncClient(transport=httpx.MockTransport(handler))


class TestAttribution(unittest.IsolatedAsyncioTestCase):
    async def test_request_carries_service_name_and_requestor(self) -> None:
        seen: dict = {}

        def handler(request: httpx.Request) -> httpx.Response:
            seen.update(dict(request.headers))
            return httpx.Response(200, json={"message": {"content": "ok"}})

        client = ChatClient("http://gw:8210", "m",
                            service_name="hive-companion-test")
        client._client = _transport(handler)
        await client.chat("sys", "user")
        await client.aclose()

        self.assertEqual(seen.get("x-service-name"), "hive-companion-test")
        self.assertEqual(seen.get("x-requestor"), "agent")

    async def test_default_service_name_is_not_blank(self) -> None:
        """A blank name lands in the telemetry table as gateway-unknown."""
        seen: dict = {}

        def handler(request: httpx.Request) -> httpx.Response:
            seen.update(dict(request.headers))
            return httpx.Response(200, json={"message": {"content": "ok"}})

        client = ChatClient("http://gw:8210", "m")
        client._client = _transport(handler)
        await client.chat("sys", "user")
        await client.aclose()

        self.assertTrue(seen.get("x-service-name"))


class TestServedModelProvenance(unittest.IsolatedAsyncioTestCase):
    async def test_substitution_is_remembered(self) -> None:
        def handler(request: httpx.Request) -> httpx.Response:
            return httpx.Response(
                200,
                headers={"X-Served-Model": "served-y",
                         "X-Original-Model": "asked-for-x",
                         "X-Routing-Reason": "rewritten to already loaded preferred"},
                json={"message": {"content": "ok"}})

        client = ChatClient("http://gw:8210", "asked-for-x")
        client._client = _transport(handler)
        await client.chat("sys", "user")
        await client.aclose()

        self.assertEqual(client.last_served_model, "served-y")

    async def test_no_headers_leaves_it_empty(self) -> None:
        def handler(request: httpx.Request) -> httpx.Response:
            return httpx.Response(200, json={"message": {"content": "ok"}})

        client = ChatClient("http://gw:8210", "asked-for-x")
        client._client = _transport(handler)
        await client.chat("sys", "user")
        await client.aclose()

        self.assertEqual(client.last_served_model, "")

    async def test_optional_tag_is_not_reported_as_a_substitution(self) -> None:
        """"model" and "model:latest" are one model, not a substitution."""
        import logging

        def handler(request: httpx.Request) -> httpx.Response:
            return httpx.Response(
                200,
                headers={"X-Served-Model": "nomic-embed-text:latest",
                         "X-Routing-Reason": "rewritten to loaded same-size"},
                json={"message": {"content": "ok"}})

        client = ChatClient("http://gw:8210", "nomic-embed-text")
        client._client = _transport(handler)
        with self.assertNoLogs(logging.getLogger("hive_companion.llm"),
                               level="WARNING"):
            await client.chat("sys", "user")
        await client.aclose()
        self.assertEqual(client.last_served_model, "nomic-embed-text:latest")

    async def test_genuinely_different_model_warns(self) -> None:
        import logging

        def handler(request: httpx.Request) -> httpx.Response:
            return httpx.Response(
                200,
                headers={"X-Served-Model": "llama3.2:3b",
                         "X-Routing-Reason": "rewritten to loaded same-kind"},
                json={"message": {"content": "ok"}})

        client = ChatClient("http://gw:8210", "asked-for-x")
        client._client = _transport(handler)
        with self.assertLogs(logging.getLogger("hive_companion.llm"),
                             level="WARNING") as logs:
            await client.chat("sys", "user")
        await client.aclose()

        self.assertIn("llama3.2:3b", "\n".join(logs.output))


class TestBackpressure(unittest.IsolatedAsyncioTestCase):
    async def test_429_is_reported_as_contention_not_a_bad_request(self) -> None:
        """The gateway's 600s slot wait timing out reads as a distinct fault."""
        def handler(request: httpx.Request) -> httpx.Response:
            return httpx.Response(429, json={"error": "gateway busy: no slot"})

        client = ChatClient("http://gw:8210", "m")
        client._client = _transport(handler)
        with self.assertRaises(LLMError) as ctx:
            await client.chat("sys", "user")
        await client.aclose()

        self.assertIn("gateway busy", str(ctx.exception))

    async def test_500_still_reports_its_status(self) -> None:
        def handler(request: httpx.Request) -> httpx.Response:
            return httpx.Response(500, json={"error": "boom"})

        client = ChatClient("http://gw:8210", "m")
        client._client = _transport(handler)
        with self.assertRaises(LLMError) as ctx:
            await client.chat("sys", "user")
        await client.aclose()

        self.assertIn("500", str(ctx.exception))


class TestTimeout(unittest.IsolatedAsyncioTestCase):
    async def test_client_timeout_exceeds_the_gateways_slot_wait(self) -> None:
        """The gateway holds a request up to 600s before forwarding.

        A client that gives up at 120s walks away from a slot it still holds,
        and the next call queues behind work nobody is waiting for.
        """
        from hive_companion.settings import Settings

        s = Settings()
        client = ChatClient("http://gw:8210", "m",
                            service_name=s.service_name,
                            timeout=s.llm_timeout_s)
        await client.aclose()

        self.assertGreater(s.llm_timeout_s, 600)
        self.assertEqual(float(client._client.timeout.read), s.llm_timeout_s)


if __name__ == "__main__":
    unittest.main()